steps:
  # Terraform init with backend config from substitution
  - name: 'hashicorp/terraform:1.11.2'
    dir: 'terraform'
    args:
      - 'init'
      - '-backend-config=bucket=${PROJECT_ID}-tfstate'
      - '-backend-config=prefix=${_PREFIX}'

  # Terraform validate
  - name: 'hashicorp/terraform:1.11.2'
    dir: 'terraform'
    args: ['validate']

  # Terraform fmt check
  - name: 'hashicorp/terraform:1.11.2'
    dir: 'terraform'
    args: ['fmt', '-check', '-recursive']

  # Terraform plan (optional check)
  - name: 'hashicorp/terraform:1.11.2'
    dir: 'terraform'
    args: ['plan', '-var=project_id=${PROJECT_ID}', '-var=region=${_REGION}']

# setup substitutions in trigger configuration
substitutions:
  _PREFIX: ''
  _REGION: ''
